"""Stub files for General category in Maya commands, command: containerView."""

from typing import Any, overload

@overload #Overload for containerView in ['query']
def containerView(itemInfo: str = ..., itemList: bool = ..., viewDescription: bool = ..., viewLabel: bool = ..., viewList: bool = ..., viewName: str = ..., query: bool = ...) -> None:
    """containerView is NOT undoable, queryable, and editable.
    
    A container view defines the layout information for the published attributes
    of a particular container. Container views can be selected from a set of
    built-in views or may be defined on an associated container template. This
    command queries the view-related information for a container node. The
    information returned from this command will be based on the view-related
    settings in force on the container node at the time of the query (i.e. the
    container's view mode, template name, view name attributes).

    Example:
    ```python
        import maya.cmds as cmds
        # Obtain a list of all available views for container1
        #
        cmds.containerView ( 'container1', query=True, viewList=True);
        # Result: [u'Animation', u'Rendering'] #
        #
        # Get a list of view items in the current view for container1
        # In this example the list returned will include only the name for
        # each item in the view.
        cmds.containerView ( 'container1', itemList=True, itemInfo="itemName", query=True)
        # Result: [u'RenderSetup', u'color', u'intensity', u'Transform', u'rotateY'] #
        #
        # Get a list of view items.
        # In this query the list returned will include the group boolean and label
        # for each item in the view.
        cmds.containerView ( 'container1', itemList=True, itemInfo="itemIsGroup:itemLabel", query=True)
        # Result: [u'1', u'RenderSetup', u'0', u'Color', u'0', u'Intensity', u'1', u'Transform', u'0', u'Rotate Y'] #
    ```

    ---
    - Args:
        - itemInfo (ii): Used in query mode in conjunction with the itemList flag. The command will return a list of information for each item in the view, the information fields returned for each item are determined by this argument value. The information fields
            will be listed in the string array returned. The order in which the keyword is specified will determine the order in which the data will be returned by the command. One or more of the following keywords, separated by colons ':' are used to
            specify the argument value.itemIndex  : sequential item number (0-based)itemName   : item name (string)itemLabel  : item display label (string)itemDescription : item description field (string)itemLevel  : item hierarchy level
            (0-n)itemIsGroup : (boolean 0 or 1) indicates whether or not this item is a groupitemIsAttribute : (boolean 0 or 1) indicates whether or not this item is an attributeitemNumChildren: number of immediate children (groups or attributes) of
            this itemitemAttrType : item attribute type (string)itemCallback : item callback field (string)In query mode, this flag needs a value.
        - itemList (il): Used in query mode, the command will return a list of information for each item in the view.  The viewName flag is used to select the view to query. The information returned about each item is determined by the itemInfo argument value. For
            efficiency, it is best to query all necessary item information at one time (to avoid recomputing the view information on each call).
        - viewDescription (vd): Used in query mode, returns the description field associated with the selected view. If no description was defined for this view, the value will be empty.
        - viewLabel (vb): Used in query mode, returns the display label associated with the view. An appropriate label suitable for the user interface will be returned based on the selected view.  Use of the view label is usually more suitable than the view name for
            display purposes.
        - viewList (vl): Used in query mode, command will return a list of all views defined for the given target (container or template).
        - viewName (vn): Used in query mode, specifies the name of the queried view when used in conjunction with a template target. When used in conjunction with a container target, it requires no string argument, and returns the name of the currently active view
            associated with the container; this value may be empty if the current view is not a valid template view or is generated by one of the built-in views modes. For this reason, the view label is generally more suitable for display purposes.In
            query mode, this flag can accept a value.
        - query (q): Query mode flag
    """
@overload #Overload for containerView in ['query']
def containerView(ii: str = ..., il: bool = ..., vd: bool = ..., vb: bool = ..., vl: bool = ..., vn: str = ..., q: bool = ...) -> None:
    """containerView is NOT undoable, queryable, and editable.
    
    A container view defines the layout information for the published attributes
    of a particular container. Container views can be selected from a set of
    built-in views or may be defined on an associated container template. This
    command queries the view-related information for a container node. The
    information returned from this command will be based on the view-related
    settings in force on the container node at the time of the query (i.e. the
    container's view mode, template name, view name attributes).

    Example:
    ```python
        import maya.cmds as cmds
        # Obtain a list of all available views for container1
        #
        cmds.containerView ( 'container1', query=True, viewList=True);
        # Result: [u'Animation', u'Rendering'] #
        #
        # Get a list of view items in the current view for container1
        # In this example the list returned will include only the name for
        # each item in the view.
        cmds.containerView ( 'container1', itemList=True, itemInfo="itemName", query=True)
        # Result: [u'RenderSetup', u'color', u'intensity', u'Transform', u'rotateY'] #
        #
        # Get a list of view items.
        # In this query the list returned will include the group boolean and label
        # for each item in the view.
        cmds.containerView ( 'container1', itemList=True, itemInfo="itemIsGroup:itemLabel", query=True)
        # Result: [u'1', u'RenderSetup', u'0', u'Color', u'0', u'Intensity', u'1', u'Transform', u'0', u'Rotate Y'] #
    ```

    ---
    - Args:
        - itemInfo (ii): Used in query mode in conjunction with the itemList flag. The command will return a list of information for each item in the view, the information fields returned for each item are determined by this argument value. The information fields
            will be listed in the string array returned. The order in which the keyword is specified will determine the order in which the data will be returned by the command. One or more of the following keywords, separated by colons ':' are used to
            specify the argument value.itemIndex  : sequential item number (0-based)itemName   : item name (string)itemLabel  : item display label (string)itemDescription : item description field (string)itemLevel  : item hierarchy level
            (0-n)itemIsGroup : (boolean 0 or 1) indicates whether or not this item is a groupitemIsAttribute : (boolean 0 or 1) indicates whether or not this item is an attributeitemNumChildren: number of immediate children (groups or attributes) of
            this itemitemAttrType : item attribute type (string)itemCallback : item callback field (string)In query mode, this flag needs a value.
        - itemList (il): Used in query mode, the command will return a list of information for each item in the view.  The viewName flag is used to select the view to query. The information returned about each item is determined by the itemInfo argument value. For
            efficiency, it is best to query all necessary item information at one time (to avoid recomputing the view information on each call).
        - viewDescription (vd): Used in query mode, returns the description field associated with the selected view. If no description was defined for this view, the value will be empty.
        - viewLabel (vb): Used in query mode, returns the display label associated with the view. An appropriate label suitable for the user interface will be returned based on the selected view.  Use of the view label is usually more suitable than the view name for
            display purposes.
        - viewList (vl): Used in query mode, command will return a list of all views defined for the given target (container or template).
        - viewName (vn): Used in query mode, specifies the name of the queried view when used in conjunction with a template target. When used in conjunction with a container target, it requires no string argument, and returns the name of the currently active view
            associated with the container; this value may be empty if the current view is not a valid template view or is generated by one of the built-in views modes. For this reason, the view label is generally more suitable for display purposes.In
            query mode, this flag can accept a value.
        - query (q): Query mode flag
    """
@overload #Overload for containerView in ['query']
def containerView(itemInfo: str = ..., ii: str = ..., itemList: bool = ..., il: bool = ..., viewDescription: bool = ..., vd: bool = ..., viewLabel: bool = ..., vb: bool = ..., viewList: bool = ..., vl: bool = ..., viewName: str = ..., vn: str = ..., query: bool = ..., q: bool = ...) -> None:
    """containerView is NOT undoable, queryable, and editable.
    
    A container view defines the layout information for the published attributes
    of a particular container. Container views can be selected from a set of
    built-in views or may be defined on an associated container template. This
    command queries the view-related information for a container node. The
    information returned from this command will be based on the view-related
    settings in force on the container node at the time of the query (i.e. the
    container's view mode, template name, view name attributes).

    Example:
    ```python
        import maya.cmds as cmds
        # Obtain a list of all available views for container1
        #
        cmds.containerView ( 'container1', query=True, viewList=True);
        # Result: [u'Animation', u'Rendering'] #
        #
        # Get a list of view items in the current view for container1
        # In this example the list returned will include only the name for
        # each item in the view.
        cmds.containerView ( 'container1', itemList=True, itemInfo="itemName", query=True)
        # Result: [u'RenderSetup', u'color', u'intensity', u'Transform', u'rotateY'] #
        #
        # Get a list of view items.
        # In this query the list returned will include the group boolean and label
        # for each item in the view.
        cmds.containerView ( 'container1', itemList=True, itemInfo="itemIsGroup:itemLabel", query=True)
        # Result: [u'1', u'RenderSetup', u'0', u'Color', u'0', u'Intensity', u'1', u'Transform', u'0', u'Rotate Y'] #
    ```

    ---
    - Args:
        - itemInfo (ii): Used in query mode in conjunction with the itemList flag. The command will return a list of information for each item in the view, the information fields returned for each item are determined by this argument value. The information fields
            will be listed in the string array returned. The order in which the keyword is specified will determine the order in which the data will be returned by the command. One or more of the following keywords, separated by colons ':' are used to
            specify the argument value.itemIndex  : sequential item number (0-based)itemName   : item name (string)itemLabel  : item display label (string)itemDescription : item description field (string)itemLevel  : item hierarchy level
            (0-n)itemIsGroup : (boolean 0 or 1) indicates whether or not this item is a groupitemIsAttribute : (boolean 0 or 1) indicates whether or not this item is an attributeitemNumChildren: number of immediate children (groups or attributes) of
            this itemitemAttrType : item attribute type (string)itemCallback : item callback field (string)In query mode, this flag needs a value.
        - itemList (il): Used in query mode, the command will return a list of information for each item in the view.  The viewName flag is used to select the view to query. The information returned about each item is determined by the itemInfo argument value. For
            efficiency, it is best to query all necessary item information at one time (to avoid recomputing the view information on each call).
        - viewDescription (vd): Used in query mode, returns the description field associated with the selected view. If no description was defined for this view, the value will be empty.
        - viewLabel (vb): Used in query mode, returns the display label associated with the view. An appropriate label suitable for the user interface will be returned based on the selected view.  Use of the view label is usually more suitable than the view name for
            display purposes.
        - viewList (vl): Used in query mode, command will return a list of all views defined for the given target (container or template).
        - viewName (vn): Used in query mode, specifies the name of the queried view when used in conjunction with a template target. When used in conjunction with a container target, it requires no string argument, and returns the name of the currently active view
            associated with the container; this value may be empty if the current view is not a valid template view or is generated by one of the built-in views modes. For this reason, the view label is generally more suitable for display purposes.In
            query mode, this flag can accept a value.
        - query (q): Query mode flag
    """
